# Generated by Django 5.0 on 2023-12-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_contestant',
            field=models.BooleanField(blank=True, default=False, help_text='Do you want toparticipate in contests?', null=True),
        ),
    ]
