# Generated by Django 5.0 on 2023-12-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter phone number e.g: +998123456789', max_length=13, null=True, unique=True),
        ),
    ]
