# Generated by Django 5.0 on 2023-12-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_customusermodel_is_contestant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='is_contestant',
            field=models.BooleanField(default=False, help_text='Do you want toparticipate in contests?'),
        ),
    ]
