# Generated by Django 5.0 on 2023-12-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_customusermodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter phone number e.g: +998123456789', max_length=13, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
