# Generated by Django 5.0 on 2023-12-18 13:50

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_customusermodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists'}, help_text='Required. Your email address.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='password',
            field=models.CharField(max_length=100, validators=[django.contrib.auth.password_validation.validate_password]),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter a valid phone', 'unique': 'A user with that phone number already exists'}, help_text='Enter phone number e.g: +998123456789', max_length=13, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
