# Generated by Django 5.0 on 2023-12-18 14:58

import user_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_customusermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists'}, help_text='Required. Your email address.', max_length=254, unique=True, validators=[user_app.validators.validate_email], verbose_name='email address'),
        ),
    ]
