# Generated by Django 5.0 on 2023-12-18 15:31

import user_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_customusermodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists'}, help_text='Required. Your gmail address. e.g: example.gmail.com', max_length=254, unique=True, validators=[user_app.validators.validate_email], verbose_name='email address'),
        ),
    ]
