# Generated by Django 5.0 on 2023-12-18 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest_app.profilemodel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest_app.contestmodel'),
        ),
    ]
