# Generated by Django 4.2.8 on 2024-01-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertmodel',
            name='job_title',
            field=models.TextField(blank=True, help_text='Experts job title.', null=True),
        ),
    ]
