# Generated by Django 4.2.8 on 2024-01-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0003_expertmodel_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertmodel',
            name='job_title',
            field=models.CharField(blank=True, help_text='Experts job title.', max_length=150, null=True),
        ),
    ]
