# Generated by Django 5.0 on 2023-12-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0004_alter_contestmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestmodel',
            options={'ordering': ('publish_date',), 'verbose_name': 'contest', 'verbose_name_plural': 'contests'},
        ),
    ]
